---
- hosts: all
  become: true
  tasks:
    - name: Transfer executable script script
      copy: src=/workspace/docker-inst.sh dest=/tmp/docker.sh mode=0777

    - name: Execute the script
      command: sh /tmp/docker.sh
